name: "Deployment Pipeline"

on:
  push:
    branches: ["master"]

jobs:
  cd:
    name: "CD Job"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload to S3
        run: |
          aws s3 cp main.tf s3://instance-user-data/terraform-modules/terraform-aws-ec2-instance-profile/
          aws s3 cp outputs.tf s3://instance-user-data/terraform-modules/terraform-aws-ec2-instance-profile/
          aws s3 cp variables.tf s3://instance-user-data/terraform-modules/terraform-aws-ec2-instance-profile/
          aws s3 cp LICENSE s3://instance-user-data/terraform-modules/terraform-aws-ec2-instance-profile/
